bjornbytes/lovr

- CMakeLists.txt
- COMPILING.md
- src/filesystem/filesystem.c
- src/headset/openvr.h
- src/lib/glfw.h
- Add instructions for compiling on (Arch) Linux.
- Linux support for `lovr.filesystem`.
- Fix some icky undefined behavior.
- Various other fixes for linux, gcc, etc.
Thanks @Jcd1230!  Addresses #14
> Linux Support

- src/headset/fake.c
Forgot to send events for the fake controller button.
Also moved the offset for the fake controller, so it's not situated at your feet.
> Fake headset - controller button event

- src/api/graphics.c
- src/graphics/graphics.c
- src/graphics/graphics.h
- src/graphics/opengl.c
An optimization for mobile devices.  On desktop this does nothing.
> lovr.graphics.discard;

- src/filesystem/file.c
- src/filesystem/file.h
> lovrFileWrite buffer can be const and therefore should

- CMakeLists.txt
- src/headset/oculus.c
> Fix Oculus driver compilation

- src/api/headset.c
- src/headset/oculus_mobile.c
- src/luax.c
- src/luax.h
- src/main.c
It's now a more general error stored in the registry instead of
in a global variable.  There are more helper functions.
I need to do a fair amount of testing on this.
> Refactor asynchronous headset render errors;

- src/core/platform_android.c.h
- src/modules/headset/oculus_mobile.c
- src/modules/headset/oculus_mobile_bridge.h
As discussed in Slack, there are two problems with this which appear to be on the lovr side:
- Driver isTouched is not being called when lua calls isTouched. It appears isDown is being called instead.
- Values returned from axis are being absolute-valued.
There is one limitation of the patch itself:
- Acceleration is not yet supported
This patch requires a patch on the "lovrapp" side.
> Oculus quest support

- src/modules/headset/oculus.c
> Fixes to Oculus Windows build

- CMakeLists.txt
animator.c was removed but only the tupfile was updated
> Fix CMakeLists.txt after animator removed

- src/api/l_texture.c
- src/modules/graphics/opengl.c
- src/modules/graphics/shader.h
- src/modules/graphics/texture.c
- src/modules/graphics/texture.h
This was a bit rushed, going to look over it later.
> Shadow samplers;

- src/core/hash.h
> core/hash.h is missing #pragma once

- src/api/l_thread.c
- src/modules/thread/channel.c
- src/modules/thread/thread.c
- src/modules/thread/thread.h
Long discussions/debugging related to channel ownership and thread safety, ultimately with a revert to the original implementation? >_>
> Channel ownership stuff

- src/modules/filesystem/filesystem.c
* Use normalize() in lovrFilesystemMount and dir_resolve
* zip_lookup was comparing strlen() to a buffer size, but this did not leave enough room for zero terminator
This fixes lodr with 0.14 because lodr mounts a directory at an absolute path.
Note this might be a performance regression, in tests dir_resolve gets called quite frequently. If this is a problem we could follow up by modifying normalize() to be a no-op on already-normalized strings.
> Filesystem fixes

- src/modules/headset/oculus.c
as mentioned on slack.
there are some situations you can get into (high load in some place or other) where the newer frame submission api will behave much more consistently, and I've noticed no negative effects.
besides, the other one is deprecated as best i can tell.
> update ovr driver to newer frame submission api

- src/modules/headset/oculus_mobile.c
> The Quest has thumbsticks, not touchpads

- src/modules/graphics/opengl.c
`GL_DEPTH_TEST` controls both whether depth testing and depth writes are enabled. So if depth testing is disabled and depth writes are enabled, `GL_DEPTH_TEST` has to be enabled and the compare mode should be `GL_ALWAYS`.
`gpu_gl.c` and `gpu_vk.c` seem to have a similar problem, but that code seems unused, so I can't test it.
> Fix when depth test is disabled but depth write is enabled

- CMakeLists.txt
Default to off unless build with emscripten
> Add webxr to CMake

- src/api/l_physics.c
- src/api/l_physics_collider.c
- src/api/l_physics_joints.c
- src/api/l_physics_shapes.c
- src/modules/physics/physics.c
- src/modules/physics/physics.h
Support for passing either numbers or vectors/quaternions to physics API. This closes #219.
> Physics API support for vectors

- src/api/l_graphics_shaderBlock.c
due to typo
I have not fully tested this code yet
> shaderBlock:send(blob) does not work

- src/api/l_filesystem.c
- src/modules/filesystem/filesystem.c
- src/modules/filesystem/filesystem.h
- src/resources/boot.lua
Introducing new config parameter which decides if save directory has precedence over app directory.
> Config parameter for save directory precedence

- src/modules/headset/headset_vrapi.c
To be consistent with the pose for controllers.
> Quest: Make tracked hands have a pose facing -Z

- src/modules/headset/headset_openxr.c
> OpenXR: Fix right actions not being marked as active in xrSyncActions call

- src/resources/AndroidManifest_oculus.xml
https://developer.oculus.com/blog/-oculus-quest-v23-how-to-update-your-app-for-90hz/
> Add Quest 2 90hz to android manifest

- src/resources/bindings_touch.json
This fixes issue https://github.com/bjornbytes/lovr/issues/246
> Added bindings to pose/base

- src/core/maf.h
need to dot with the axes to not have bizarre results.
> fix mat4_lookAt translation offset

- CMakeLists.txt
Some tasks need to be taken care of:
> Fixes for Big Sur and M1

- CMakeLists.txt
- src/core/os_android.c
- src/modules/headset/headset_vrapi.c
- Fix typos after "os" refactor
- Fix CMake finding javac
> Fix Android build

- src/modules/audio/audio.c
> Hold lock when changing geometry (prevents crash)

- src/api/l_headset.c
- src/modules/headset/headset.c
- src/modules/headset/headset.h
- src/modules/headset/headset_desktop.c
- src/modules/headset/headset_oculus.c
- src/modules/headset/headset_openvr.c
- src/modules/headset/headset_openxr.c
- src/modules/headset/headset_pico.c
- src/modules/headset/headset_vrapi.c
- src/modules/headset/headset_webxr.c
- src/resources/boot.lua
- src/resources/webxr.js
This add support for OpenXR experimental overlay, mostly looking for direction on where to go.
> RFC: OpenXR Overlay

- src/api/l_filesystem.c
Adds #427 functionality. Almost no code duplication.
> All-in-one plugins lua loader

- src/modules/headset/headset_vrapi.c
> VrApi viewangles with 3DOF fix

- CMakeLists.txt
- src/modules/audio/spatializer.h
u changed audio.c but not the other two files
> Fix incomplete LOVR_ENABLE PHONON/OCULUS define change

- src/core/os_win32.c
os_vm_init, os_vm_free, os_vm_commit, os_vm_release for Windows
> Make GPU branch compile on Windows

- src/api/l_math_vectors.c
Still discussion going on in #491 so consider this TBD.  An `__eq` metamethod won't work currently because temporary vectors are lightuserdata, which doesn't support `__eq`.
> Add :equals method to vector objects;

- src/modules/graphics/font.c
https://github.com/bjornbytes/lovr/issues/546
> Keep winding with flip

- etc/boot.lua
- src/main.c
- src/modules/filesystem/filesystem.c
The file will be treated as main.lua.
Its directory will be treated as the source.
> Allow passing a file to lovr;

- src/modules/graphics/graphics.c
Issue became apparent with back face culling:
```
function lovr.draw(pass)
pass:setCullMode('back')
local pose = mat4(0, 1.5, -1)
:scale(0.2)
:rotate(lovr.timer.getTime(), 0,1,0)
pass:cylinder(pose, true, nil, nil, 12)
end
```
> Fix cylinder's triangle winding and normals

- src/modules/audio/audio.c
These comments would have helped me when I was reviewing the code yesterday.
> Minor comments on audio.c

- src/api/l_graphics.c
stumbled over this odd-looking line while taking a look at the PBR Lighting sample.
> fix wrong loop limit in lovr.graphics.newShader

- CMakeLists.txt
- etc/Activity.java
- src/core/os_android.c
> Android package rename via CMake

- src/api/l_physics_world.c
- src/modules/physics/physics.c
- src/modules/physics/physics.h
```lua
world:queryBox(vec3(), vec3(1), function(shape)
if job_is_finished then
return false -- early exit
end
end)
```
> World query early exit
