README.md
If you clone the OpenVR repo as it currently stands, you are unable to compile LÖVR from source. It appears LÖVR is targeting v1.0.3 (and I have confirmed the build works as expected when compiling against this release).
I also included a small typo in the README regarding the `-DOPENVR_DIR` argument.
Fixes #4.
Note: This has been tested only on Mac OSX.
=> Update README to require OpenVR v1.0.3

src/api/event.c, src/audio/audio.c, src/event/event.c, src/event/event.h, src/filesystem/filesystem.c, src/graphics/graphics.c, src/headset/headset.c, src/lib/lua-enet/enet.c, src/lovr.c, src/lovr.h, src/main.c, src/math/math.c, src/physics/physics.c
This is an alternative to #29. lovr.event.quit and return-from-run() both support the string "restart" in place of an exit code. When this happens, the program reruns itself in a new, isolated environment. In Emscripten, no reboot occurs and the program only quits. If either receive an unexpected value (something other than a number, nil or a string other than "restart") there is an error.
I am making this change with the intent of enabling a feature where lovr auto-restarts on file changes (either in a future PR or in a personal fork I use).
Here is a test program I use to verify it is working.
```
local total = 0
print("BOOT")
function lovr.update(dt)
total = total + dt
if total > 5 then
print("QUIT")
lovr.event.quit("restart")
end
end
function lovr.draw()
lovr.graphics.print('oh wow', …
```
=> Restart-without-quit support: lovr.event.quit("restart")

src/headset/webvr.c
getBoundsGeometry implementation was dropped with 11586e8
but not in HeadsetInterface.
=> remove webvrGetBoundsGeometry reference from webvr.c

src/headset/fake.c
Currently left-click is used for both mouselook and trigger, which means it's impossible to mouselook without triggering
=> Switch trigger to right-click when using fake headset

src/api/audio.c
Checks for file not found and file-not-understood cases.
=> Error message instead of crash on invalid audio.newSource call

src/api/types/mesh.c, src/graphics/mesh.c, src/graphics/mesh.h
Some features remain to be implemented, these are marked with TODOs.
Currently it is not allowed to attach a mesh which itself has attachments.
=> Implementation of mesh:attachAttributes(), with instance divisor

src/headset/headset.h, src/headset/openvr.c
There seems to be a memory alignment issue on linux and mac that causes every button press to be reported as 'system'.
Please see this SteamVR issue for reference:
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/35
=> Fix controller button detection for linux and mac

src/headset/headset.h
In current lovr master, the first item in the ControllerButtons array (CONTROLLER_BUTTON_UNKNOWN) is NULL, which means luaL_checkoption interprets ControllerButtons as a 0-length array and controller:isDown always fails with an error message like "bad argument #1 to 'isDown' (invalid option 'trigger')"
There are two possible solutions to this
1. Reorder the ControllerButton enum so CONTROLLER_BUTTON_UNKNOWN is last instead of first
2. Add "unknown" to ControllerButtons, which would mean the "unknown" button could be queried (?)
This patch implements solution 1
=> Fix ControllerButton ordering, which broke isDown

.gitignore, src/api/graphics.c, src/api/headset.c, src/graphics/graphics.c, src/graphics/graphics.h, src/headset/fake.c, src/headset/headset.h, src/headset/oculus.c, src/headset/openvr.c, src/resources/lovr.js
Adds the ability to mirror specific eyes.  Convenient for certain situations.  Implementation seems kinda messy, I wish it didn't use 2 variables.
To make it work with OpenVR/Oculus, plan is to add uv offset parameters to `lovrGraphicsFill` and use that to blit half of the Canvas when mirroring (also those parameters will be exposed to Lua).
=> Mirror eyes

src/graphics/graphics.c, src/graphics/graphics.h, src/graphics/opengl.c, src/resources/shaders.c
This solves problems with transparency and depth testing when rendering fonts, but subtly changes the appearance of rendered text.  I would say that text seems to be a little more "shimmery" when viewed from far away now.  My guess is that the font shader is not antialiasing properly.
=> Use alpha to coverage and alpha test for text;

src/lib/sds/sds.h, src/luax.h
Here are 2 small fixes that I remember fixing the build on… … some platform or other. I don't remember what platforms.
luax_traceback is currently used in oculus_mobile.c, so it needs to be in the header. That's reasonable.
I cannot exactly remember why the sds.h change was needed. I think maybe I wanted to include sds.h in a .cpp file in my fork. Maybe that's not a fix worth including in main lovr because it contains no cpp files. But the change seems to be harmless.
=> Small portability compile fixes in headers

src/api.h, src/api/graphics.c, src/api/types/shader.c, src/api/types/shaderBlock.c, src/graphics/graphics.h, src/graphics/opengl.c, src/graphics/shader.h
Allows you to read back values from a ShaderBlock.
- This is also probably useful for Shaders and their uniforms.
- This creates SO MANY tables.  It feels so bad to expose this.  But
also it's the only way to read values back from a compute operation,
so it's pretty indispensable.  In the future there could be a Blob
variant.
- readable and writable are confusing now, since writable means "write from shader" and readable means "read from Lua".  Proposal to change writable to shaderwritable?  Anything better?
=> ShaderBlock:getValue; Shader:send vector fixes;

src/api/data.c, src/api/event.c, src/api/types/curve.c, src/data/audioStream.c, src/data/soundData.c, src/data/textureData.c, src/filesystem/filesystem.c, src/graphics/model.c, src/graphics/opengl.c, src/graphics/shader.c, src/util.c
Some more questions:
- Should there be some kind of allocation helper so you don't need
to always check the result?
- Throwing an error on OOM is convenient and is probably correct 90%
of the time, it even provides a nice error message instead of a
nil dereference somewhere.  But it's inflexible.  Is it the right
thing to do?
=> Always check malloc result; Less calloc;

src/api/graphics.c, src/graphics/graphics.c, src/graphics/graphics.h, src/platform/glfw.h
Adds `lovr.graphics.getPixelDensity` to determine the density of pixels per screen coordinate.  The graphics module is the best place for it right now, but hopefully soon there is a better place for window-related stuff.
=> Window pixel density

src/core/maf.h
I'm not sure if you actually want this in master or not. but just in case:
mat4_transform ignores the final row of the matrix, which normally contains scale data. This is fine for modelview matrices, which is all lovr currently uses mat4_transform for. However it fails if you ever use mat4_transform on a projection matrix.
mat4_transform_project takes the final row into account, so you can use it with projection matrices. This was useful in my fork and might be useful to have around in lovr someday later.
=> mat4_transform_project in maf.h

src/core/ref.h
This commit is pretty out there and if you want to deny it I'd be fine with that. This replaces the ref.h solution in my other PR.
It turns out there are a set of GCC atomics that are supported by every compiler I can find that supports C11 atomics, but which do not have the C++ incompatibility. This patch uses the GCC atomics where possible but keeps C11 as a fallback (with a helpful error message if the C11 header is illegally included in C++).
Check for GCC version >=4.7 [covers GCC or, theoretically, Intel C Compiler] or __has_builtin(__atomic_add_fetch) [covers Clang]. If either of these are found, use the GCC atomic builtins instead of the C11 builtins.
Also: Gates Microsoft atomics on _MSC_VER, not _WIN32, and defines one of LOVR_HAS_MSVC_ATOMICS, LOVR_HAS_GCC_ATOMICS or …
=> ref.h compiles in C++

src/core/maf.h, src/lib/sds/sds.h
Although Lovr is pure C, users might fork Lovr or attempt to load binary Lua plugins that reference the header files. My own fork of Lovr contains a number of C++ files. I think it's worth making the Lovr headers C++-compatible as long as the changes do not create an inconvenience for mainline Lovr dev.
This PR contains three patches to make headers C++ friendly:
- Patch SDS to detect __cplusplus and not use empty arrays when present
- Patch a line in maf.h to use a variable instead of an inline array
- Put an #error in core/ref.h detecting __cplusplus and explaining that we are using C++-incompatible C11 atomics-- I have some ideas about how to "fix" this properly at some future point but for now I think a useful error message is good enough
See commit messages for more detail
All of …
=> Make it possible to include lovr headers from C++

src/modules/headset/oculus_mobile.c
Because of how and when draws occur in our Oculus Mobile path, during a restart it would attempt to draw a frame after lovrGraphicsDestroy() is called, leading to a crash in lovrGraphicsSetCamera(). This blocks draws until the restart is finished and renderTo() has been called (conveniently detectable using the existing state.renderCallback).
=> Fix crash with lovr.event.quit("restart") on Oculus Mobile

src/api/l_event.c, src/modules/event/event.c, src/modules/event/event.h
Note: I **DO NOT KNOW** if this is the correct fix, bjorn would know better.
l_event.c was processing a thread-related event and in the process using a thread struct, even when LOVR_ENABLE_THREAD is undefined and threads do not exist. I instead made receiving that event an assert failure.
=> Fix -DLOVR_ENABLE_THREAD=OFF compile

src/modules/filesystem/file.c
Previously, this program
```
function lovr.update(dt) lovr.filesystem.append("/test123", lovr.timer.getTime()) end
```
would fail in lovr because lovrFileWrite required the file to be in write mode (not append)
The `src/modules/filesystem/filesystem.c` change has no effect. I only changed it because I **assume** this was done by mistake, and it was confusing me.
=> Fix lovr.filesystem.append()

src/modules/headset/desktop.c
This doesn't have to be merged, but: This makes it so when you reset, for example using F5 or lovr-lodr, the fake camera in "desktop" does not reset positions. This is IMO more convenient because the fake camera isn't an "in-game" thing, rather it's a simulation of a vr headset. VR headsets don't reset their positions when the game does…
=> Don't reset camera position of desktop driver on reset

src/api/l_model.c
This is not efficient (and maybe should be documented as such?) but I found it useful for debug, like
local materialCount = model:getMaterialCount()
print("Model materials: ", materialCount)
for i=1,materialCount do
print(i, model:getMaterialName(i))
end
=> model:getMaterialName(idx)

src/modules/headset/oculus_mobile.c
This means Lua print() statements can be uniquely filtered out vs anything else (because internal Lovr logging uses loglevel DEBUG and lovr errors use loglevel WARN).
I don't feel strongly about this one.
Explanation of loglevels: https://developer.android.com/ndk/reference/group/logging
=> Oculus mobile: Promote Lua print() statements to INFO

src/modules/headset/oculus_mobile.c, src/modules/headset/oculus_mobile_bridge.h
This commit is a fist pass. It only does "simple" vibrate (hard on/off). It supports duration but not frequency. Supporting frequency will probably require Oculus to document their "haptic buffer" function, which currently is IMO not clear enough to work with. I have filed a bug about this: https://developer.oculus.com/bugs/bug/533528907451560/
However even this incomplete version of vibrate probably gives us feature parity with some other platforms.
This commit requires a corresponding commit in the lovr-oculus-mobile repo (see mobile-1.patch, attached:
[mobile-1.txt](https://github.com/bjornbytes/lovr/files/3660168/mobile-1.txt) )
See also attached my test program (as written requires lovr-ent) 
[vibrate.txt](https://github.com/bjornbytes/lovr/files/3660170/vibrate.txt)
=> Vibrate function for Oculus Quest

src/api/api.c, src/api/api.h, src/main.c, src/modules/headset/oculus_mobile.c
I discussed this with @bjornbytes offline, it should now show the lovr error screen and message on oculus mobile instead of crashing in the cases I was seeing.
=> Throw lua errors in the error handler

Tuprules.tup, src/modules/filesystem/filesystem.c
This causes the filesystem module to attempt to mount a `.lovr` file from the macOS bundle, which is also considered fused mode.  This is the main way of doing distribution on macOS (appending a zip to the executable doesn't work).
Gotta figure out how to clean this up...it was easiest for me to test it out by just using the raw objective C runtime, but maybe there is a better approach/place for it.
=> Load .lovr files from the macOS app bundle;

src/api/l_world.c
This appears to have been missed in commit 22fe333, and makes it impossible to use a custom collision resolver (the code for a default collision resolver in the docs results in a "bad argument #1 to 'collide' (Shape expected, got userdata)")
=> Fix World:Collide to use new luax_checkshape

src/modules/headset/desktop.c
Looks like this:
Downside: Right-clicking no longer taps in the center of the scene. Upside: you can actually move the controller and emulate much  more advanced behaviors without having to launch into VR :) I think it's totally worth it.
I noticed a bit late that that some similar stuff is done in `desktop_update`. Should I refactor this to not be on demand, but instead populate a state.leftHandTransform in update instead?
=> Desktop driver: Move left controller with mouse

src/modules/filesystem/filesystem.c
Calling objc_msgSend with its vararg signature will only work most
of the time, and fail very weirdly when it doesn't. It's weird,
but you're supposed to always cast it to the signature of the
selector you're calling.
I think this is even required when building on Catalina, or for arm64?
=> Cast objc_msgSend before calling it

CMakeLists.txt
TARGET_FILE_DIR will do the right thing regardless of VS version
=> Fix move_dll for VS2019

src/api/l_shapes.c, src/modules/physics/physics.c, src/modules/physics/physics.h
Here's a simple project to test it:
```lua
function lovr.load()
world = lovr.physics.newWorld()
collider = world:newBoxCollider(0, 5, -4, .1)
box = unpack(collider:getShapes())
sensor = world:newBoxCollider(0, 1, -4, 4, 2, 1)
sensor:setKinematic(true)
sensorShape = unpack(sensor:getShapes())
sensorShape:setSensor(true)
end
function lovr.update(dt)
inSensor = false
world:update(dt, function()
world:computeOverlaps()
for a, b in world:overlaps() do
local colliding = world:collide(a, b)
if colliding and (a == box and b == sensorShape) or (a == sensorShape and b == box) then
inSensor = true
end
end
end)
end
function lovr.draw()
lovr.graphics.setColor(0xffffff)
lovr.graphics.box('fill', vec3(collider:getPosition()), vec3(box:getDimensions()), quat(collider:getOrientation())) …
```
=> Shape:isSensor; Shape:setSensor;

.gitignore
Visual Studio Code creates .vs directories when you tell it to open a directory as a project.
Might as well put them in .gitignore?
=> Include .vs in .gitignore (visual studio code)

.gitmodules
The Physfs dep has been removed, but it is still listed in .gitmodules. This is confusing my third party git client very badly.
=> Remove physfs from .gitmodules

src/core/hash.h
Minor one-line fix to make lovr headers compatible with C++. No functional difference
=> Fix C++ compilation

CMakeLists.txt, src/modules/filesystem/file.c, src/modules/filesystem/file.h
This code path is not used anywhere in this commit, but aids in developing Lovr addons.
(This does increase executable size slightly without providing an obvious benefit. There may be other options, such as making this an external library. The **important** thing to me, as a Lovr addon developer, is that there be a "reliable" API— ie, if the C api brings back File someday, I want to know I'm already targeting the correct function signatures to hook into it.)
=> Bring back old File C API (read-only currently)

CMakeLists.txt, src/lib/stb/stb_image.c, src/lib/stb/stb_image.h
Uses the tinycthread library we are already using. This makes loading images in multiple threads concurrently safe. (Currently running newModel and newTexture in separate threads will cause misbehavior.)
Has a kind of safety switch to prevent removing the threadlocal change by accident.
Support changes
* Upgrade stb_image from v2.12 to v2.23
* Adds a new CMake variable LOVR_USE_THREADLOCAL, by default on
=> Patch in thread local storage for stb_image vflip

src/api/l_data.c, src/api/l_data_audioStream.c, src/modules/audio/audio.c, src/modules/audio/source.c, src/modules/data/audioStream.c, src/modules/data/audioStream.h
Gives LÖVR the ability to play runtime-generated audio (in addition to playing audio from ogg files on disk). This will be used in Alloverse to play voip audio between multiplayer users, but could also be used to generate audio or music programmatically.
This PR adds two APIs:
* `lovr.audio.newAudioStream(bufferSize, channelCount, sampleRate)` creates a "raw" AudioStream which can only get audio from `AudioStream:append()` and not from decoding a file on disk
* `AudioStream:append(blob)` appends raw PCM sound data for playback ASAP.
Tasks remaining before PR is mergeable:
=> Real-time raw AudioStreams

src/modules/graphics/canvas.c, src/modules/graphics/opengl.c, src/modules/headset/oculus_mobile.c, src/modules/headset/oculus_mobile_bridge.h
This is a change that shifts the responsibility of the creation
of OpenGL framebuffers from vrapi-provided swapchain texture handles.
Previously, the LovrApp component of lovr-oculus-mobile was creating
framebuffers and passing native framebuffer IDs to lovr.  With this
change, lovr-oculus-mobile passes vrapi's swapchain textures to lovr
unmodified.  This allows lovr to create canvases using its conventional
method and also means that the properties of the canvases are no longer
hardcoded, so things like resolution and multisampling can be
customized.
There were also some issues with multiview canvases in LÖVR due to some
misconceptions about how multisampled multiview rendering works.  These
issues have also been fixed in this PR as well.
=> Android Canvas

src/api/l_audio_microphone.c, src/api/l_data_audioStream.c, src/api/l_data_soundData.c, src/api/l_data_textureData.c, src/api/l_graphics.c, src/modules/audio/microphone.c, src/modules/audio/microphone.h, src/modules/audio/source.c, src/modules/data/audioStream.c, src/modules/data/rasterizer.c, src/modules/data/soundData.c, src/modules/data/soundData.h, src/modules/data/textureData.c, src/modules/data/textureData.h, src/modules/graphics/opengl.c, src/modules/headset/openvr.c
Just some small fixes that ease the handling of audio:
* `SoundData` gets a `Blob*` ivar instead of `Blob`. This means the blob can be accessed as a proper child object.
* In that vein, `SoundData` gets `SoundData:getBlob()`. This way, you can `getString` etc on the blob in the `SoundData`, and use the data with other APIs more easily
* Slightly related, `Microphone:getData()` gets a buffer size parameter. I was originally going to implement a ring buffer class, but I only need it to buffer microphone data before it's ready to be sent off to the network. Turns out OpenAL already has a ringbuffer internally, and by adding a parameter to say how much data you want to chop of NOW, we can utilize that ringbuffer downstream. This makes my code much easier.
The last one there is going to make …
=> Sound adjustments: SoundData has-a blob, and mic sample size getter

src/api/l_graphics.c, src/modules/graphics/opengl.c, src/modules/graphics/shader.c, src/modules/graphics/shader.h
The previous implementation relied on `glShaderSource` inferring source lengths when the lengths weren't specified. This relies on the sources being properly null-terminated, however, which isn't the case due to file loading changes which now use pointer + length. This could cause intermittent crashes.
Changing this on the shader side meant adding some extra arguments for passing around shader source lengths. For most of the other cases, where we're using string literals as the sources, we can just specify -1 as the length, since OpenGL will calculate the string length for you any time the length is negative.
Fixes #201
=> Compile shaders using source lengths

src/api/l_headset.c, src/core/maf.h, src/modules/headset/desktop.c, src/modules/headset/headset.h, src/modules/headset/oculus.c, src/modules/headset/oculus_mobile.c, src/modules/headset/openvr.c, src/modules/headset/openxr.c, src/modules/headset/webvr.c, src/resources/webvr.js
See #198 
- `lovr.headset.getViewCount`
- `lovr.headset.getViewPose`
- `lovr.headset.getViewAngles`
Todo
- Internal API: might be better off as `getViews(views[2], &count)`, for many reasons
- External API: nil vs. errors, naming
Maybe
=> Headset views;

src/resources/shaders.c
Yesterday I said:
> Also, I just tested out the compute shaders, works nicely on this end, thanks!
Turns out I spoke too soon, that was just the SSBOs working.
GLES doesn't like `#version 430` for compute, it wants `#version 310 es`. We can conditionally compile that!
=> Use different compute #version with OpenGL ES

src/modules/headset/oculus_mobile.c, src/modules/headset/oculus_mobile_bridge.h
Implements `lovr.headset.getDisplayFrequency` (and reorders getDisplayTime).
Requires lovr-oculus-mobile to actually write the data (bjornbytes/lovr-oculus-mobile#display-frequency), but this should be merged first so lovr-oculus-mobile can get the new bridge field.
=> oculus_mobile: lovr.headset.getDisplayFrequency;

src/modules/headset/oculus_mobile.c, src/modules/headset/oculus_mobile_bridge.h
Implements `lovr.headset.wasPressed` and `lovr.headset.wasReleased` for oculus_mobile.
Eventually lovr-oculus-mobile will write the data (bjornbytes/lovr-oculus-mobile#android-button-events).
=> oculus_mobile: Expose button changed states;

src/modules/headset/oculus_mobile.c, src/modules/headset/oculus_mobile_bridge.h
Implements `lovr.headset.getBoundsDimensions` (and individual width/depth accessors) for oculus_mobile.
=> oculus_mobile: Expose bounds dimensions;

src/resources/shaders.c
Skybox was failing with error "Regular non-array variable 'uv' may not be redeclared ". Did something go wrong when lovrMain {} got backed out?
=> Fix lovr.graphics.skybox()

src/core/ref.h
Okay. This… one's… weird.
We pass ref directly to _InterlockedIncrement on Windows. However the argument to _InterlockedIncrement is declared volatile and Ref is not declared volatile. Apparently this is fine in C, and it is fine in C++ in both Clang and MSVC 2017. However if you compile Lovr in MSVC 2019, and you have added a .cpp file which #includes ref.h (which is something I have done in my private fork), this will fail. This patch adds a cast which only activates when ref.h is included into a C++ file.
I do not know if this is the best way to do this. It would be better to add a compile flag that tells MSVC 2019 it is okay to pass a `long *` to a `volatile long *` without a cast. But I don't know how to do that.
=> Fix ref.h in recent MSVC when compiled as C++

src/resources/boot.lua
Oculus gives us the mirror texture "upside down" compared to every other driver, so flip it rightside up before drawing in boot.lua.
**WARNING: I HAVEN'T TESTED THIS ON MASTER YET**. It worked a few months ago. I'll have time to test it next week. EDIT: I tested it, it worked as expected
=> Y-flip mirror texture on Oculus

src/modules/headset/oculus.c
Combine this with an upgrade to Oculus SDK 1.43 (which fixes the frame 3 glitch) and https://github.com/bjornbytes/lovr/pull/128 , and the Oculus mirror is now very nice. Now if only we could do something about rendering when the headset comes off…
I'm not sure if we should set this to LeftEye (which I did) or to 0 (would show the eyes "flat" but side-by-side, like OpenVR). Maybe it would make sense to have a conf.lua value at some point indicating whether people would rather have the mirror be stereo or mono.
=> Instead of showing post-distortion in Oculus mirror, show the left eye (no stereo)

src/core/maf.h
At some point I convinced you to add `mat4_transform_project` to maf.h (if you look at the blame, it is my function). At the time I believed it was a specialized version of `mat4_transform`. It is not. It does literally nothing `mat4_transform` doesn't, except it is BUGGY and produces literal garbage.
Patch removes the bad function and adds comments to mat4_multiply and mat4_transform to make it less likely the next person will make the same mistake I did.
=> Kill mat4_transform_project

src/modules/headset/oculus.c
fixes the todo. implemented with a timer so that durations should work, tested working with the following:
```lua
function lovr.draw()
for i, hand in ipairs(lovr.headset.getHands()) do
lovr.headset.vibrate(hand, lovr.headset.getAxis(hand, 'trigger'), 0, 0)
local x, y, z = lovr.headset.getPosition(hand)
lovr.graphics.sphere(x, y, z, .1)
end
end
```
it updates the controller haptics state every frame, but I have no reason to believe this is a problem from the docs or test.
=> implement haptics on oculus desktop

src/api/l_event.c, src/modules/event/event.h, src/modules/headset/oculus_mobile.c, src/resources/boot.lua
After the changes to add a "cookie" to `lovr.event.quit("restart")`, restarting was broken on Oculus Mobile. This patches oculus mobile so restarting and the cookie work.
In addition, after a slack conversation, these changes were made to quit("restart") and the cookie:
- lovr.event.quit("restart") no longer supported
- lovr.event.quit no longer accepts restart "cookie"
- When lovr.event.restart() called, lovr.quit is not called, instead lovr.restart() is called
- Value returned from lovr.restart() becomes the cookie
- lovr.event.quit receives the lovr.event.quit() return code as an argument
(The return values from lovr.run() are not changed, but boot.lua picks the return values differently and the event code is simplified to remove the cookie plumbing.)
These changes mean that a cookie …
=> Oculus mobile "restart cookie" support; lovr.event.restart() changes

src/api/l_physics_collider.c, src/modules/physics/physics.c, src/modules/physics/physics.h
The conversion from `angle,ax,ay,az` to quaternion is already done in physics module.
=> Fix collider setOrientation() and setPose()

src/api/l_physics_world.c, src/modules/physics/physics.c, src/modules/physics/physics.h
Inertia matrix has to be calculated with algorithm specific for each
shape. Without calculated matrix the physics behaves very floaty and
slowed down.
This commit will fix physics for most users that only use world:new___Collider(). 
It will still not work correctly if shapes are manually added to collider. For that case the inertia matrix would have to be re-calculated for each new shape, which is ...complicated. It needs more discussion because API would have to be adapted.
I also increased MAX_CONTACTS to 10 because 4 is too low. The number represents maximum handled simultaneous collisions as well as connected joints.
=> Initialize inertia information for new colliders

src/api/l_physics_world.c
When creating colliders, setting gravity or casting rays on world,
arguments accept either coordinate numbers as before, or vec3 objects.
For functions that receive more than one set of coordinates, any
combination of coordinates and vectors is accepted.
Work towards solving #219, only World API is included here.
=> Physics world accepts both vec3 and number coords

src/api/l_graphics_shaderBlock.c
Every method in shaderBlock() asserts that a uniform exists before reading its structure, except getOffset, which just hauls ahead and reads it, causing a segfault. Patch adds the assert in getOffset as well.
Here's my test code
```
function lovr.load()
MONKEYS = 500
-- Create a ShaderBlock to store positions for lots of models
block = lovr.graphics.newShaderBlock('uniform', {
modelTransforms = { 'mat4', MONKEYS }
}, { usage = 'static' })
block:getOffset("doesntExist")
end
```
=> shaderblock:getOffset() crashes on nonexistent field

src/modules/audio/audio.c
With the check for samples==0 being done BELOW the assert for offset+samples<soundData->samples,
setting samples to 0 and then having more samples available in the mic than present in
the created buffer would cause buffer overrun
=> lovrMicrophoneGetData: fix potential buffer overrun

src/api/l_physics_joints.c, src/api/l_physics_world.c, src/modules/physics/physics.c, src/modules/physics/physics.h
ERP (Error Reduction Parameter) controls the amount of corrective force
applied to colliders that belong to joints. With value of 0, no
corrective force is applied and joined colliders will drift off in time.
With value close to 1, strong force will ensure precision of joints.
CFM (Constraint Force Mixing) controls the rigidness/springiness of
simulation. Lower values make constraints "hard" and result in more
unstable simulation, while values closer to 1 give spongy and soft
simulation.
=> Physics simulation access to global ERP and CFM

src/modules/headset/headset_oculus.c
=> Oculus driver: Fix bug where vibration never stops once it has started

src/api/l_math_vectors.c
Rotation and scaling is lost, only position is extracted from mat4.
Allows `vec3(mat4Obj)` instead of more verbose `vec3(mat4obj:mul(0,0,0))` and `vec3(mat4obj:unpack())`.
=> Initialize vec3 from mat4

src/core/os_linux.c
I added header files with #include to prevent the implicit declaration warnings and the dereferencing pointer to incomplete type error. I also fixed a typo in function size_t lovrPlatformGetExecutablePath(char* buffer, size_t size). See Issue #275.
=> Fixed errors & warnings when compiling on linux

src/modules/graphics/graphics.c
Neither Quest nor Pico check for null on its out-params.
Better to send in dummy params to avoid nulls.
=> fix crash in lovrGraphicsGetPixelDensity

src/modules/headset/headset_pico.c
Pico wasn't building because of a new missing platform function.
Controller were at the wrong location due to a missing offset.
=> Fix pico: build error, and controller location

src/core/os_android.c
There are two HOME keys defined in keycodes.h, the previously used
doesn't work and is labeled with the following comment: "This key
is handled by the framework and is never delivered to applications."
=> Fix definition of HOME key on Android

src/api/api.h, src/api/l_physics.c, src/api/l_physics_shapes.c, src/api/l_physics_world.c, src/modules/physics/physics.c, src/modules/physics/physics.h
The trimesh collider support seems to be working properly now.
Few still unsolved issues:
- arrays for vertices and indices are manually allocated in l_lovrWorldNewMeshCollider() and they are not freed in dGeomTriMeshDataDestroy(), destroying trimesh colliders will leak memory
- haven't made API to construct a shape and then add it to collider like other shapes have - would lead to substantial code duplication
- invalid index table winding (CW) leads to negative mass and ODE crashes - would be nice to detect and correct
Even with these issues the feature is already useful for most purposes.
=> Support for trimesh shape colliders

src/resources/boot.lua
with a pcall, like the requires above. so if there
is no matching headset driver, the module is just
turned off.
=> Allow lovr.headset.init to fail

src/modules/headset/headset_openxr.c
Monado requires that the .type field is always set, and that poses are completely valid including setting `w` to 1.0f.
=> OpenXR: Fixes for implementations that are more strict with validation

CMakeLists.txt
This is done by omitting the --ks-pass argument completely
=> Add a check so apksigner works even without ANDROID_KEYSTORE_PASS

src/api/l_graphics.c
It seems to me like that lovrRelease will delete textureData->blob immediately,
which means the windowing system later can't use it because it's already freed.
There's already a free on line 378 which looks more correct.
Also, icon appears flipped if 'flipped' is set to true here on Linux. Is GLFW
inconsistent between linux and windows, or should it indeed be false?
=> don't free window icon before it's used

src/api/l_thread.c
Without this, the error handler only prints the _main thread's
error handler's_ stack trace
=> Stack trace when background thread crashes

src/api/l_physics_shapes.c
Shape without attached collider cannot be positioned or oriented. Trying
to do so results in ODE crash. Better to throw a more descriptive error.
=> Check if shape can be positioned and oriented

src/api/l_physics_collider.c, src/api/l_physics_world.c
Zero as default makes more sense. Colliders can come to full stop which
allows them to go to sleep for CPU optimization. Also in zero gravity
colliders crawling through air with 0.01 velocity are infuriating.
=> Change default damping threshold to zero

src/api/l_math.c
This `lovr.math.newCurve(n)` variant is already described in API
documentation, now it is implemented.
=> Create empty curve with specified number of points

src/core/maf.h
The caluclated angle is forced to PI if cos(angle) falls outside the
[-1, +1] range due to floating point precision error.
=> Fix NaN return from mat4 unpacking

src/resources/boot.lua
> 
Error occurred while trying to display another error: Temporary vector space exhausted. Try using lovr.math.drain to drain the vector pool periodically.
This would happen because the new error handler has fancy graphics and uses temprary vectors, but doesn't drain the temporary vector pool. Now it does :)
=> fix crash in error handler when running out of vectors

src/api/l_headset.c
In boot.lua, it assumes that lovr.headset.init will assert if no driver
is available. This was previously only true on the first call to it,
since after it's initialized, it'll just return early and won't assert.
This will later crash since your lua code will now see a lovr.headset
being available, but calling anything in it will crash since
lovrHeadsetDisplayDriver is NULL
=> on lodr restart, make sure lovr.headset is nil'd if none is available

src/resources/bindings_touch.json
Now controllers work without https://github.com/bjornbytes/lovr/pull/336 Possibly the testing environment is unreliable. I revert the change, so there is no chance of breaking things for someone else.
=> Reverting binding to base

src/core/fs.c
At least on my Linux system it'd overwrite the contents of the file each time.
=> filesystem.append didn't append in Unix

src/modules/headset/headset_openxr.c
fixes
```
XR_ERROR_VALIDATION_FAILURE: xrGetSystemProperties(properties->type == 4294967295)
Error:
OpenXR Error: XR_ERROR_VALIDATION_FAILURE at ../src/modules/headset/headset_openxr.c:546
```
=> initialize XrSystemProperties type

src/api/l_math_vectors.c, src/core/maf.h
lookAt() returns view matrix that can be used to transform the camera
perspective. target() returns model matrix that is used to change
model transform. Results are matrix inversions of one another. Now both
functions exist it is possible to use right one and avoid extra matrix
inversion.
=> Add mat4:targetAt and modify the mat4:lookAt

src/api/l_audio.c, src/api/l_data_soundData.c, src/modules/audio/audio.c, src/modules/audio/audio.h, src/modules/audio/spatializers/dummy_spatializer.c, src/modules/data/soundData.c, src/modules/data/soundData.h, src/modules/headset/headset_pico.c
I realized it's silly to have two separate ring buffer abstractions. Nicer to back mic capture by a proper SoundData. Then I can even move that over a channel to another thread, and read from it without a lock! (E g move mic data _directly_ from audio thread to network thread, without touching main thread).
I think the API is nicer too.
This is based on top of https://github.com/bjornbytes/lovr/pull/347 .
=> New API for mic capture

.gitmodules, CMakeLists.txt, src/api/l_audio.c, src/modules/audio/audio.c, src/modules/audio/audio.h, src/modules/audio/spatializer.h, src/modules/audio/spatializers/dummy_spatializer.c, src/modules/audio/spatializers/oculus_spatializer.c, src/modules/audio/spatializers/oculus_spatializer_math_shim.h, src/modules/data/soundData.c
This is a large patch which adds a new Oculus Audio spatializer. Oculus Audio is slightly different from the dummy spatializer in a few ways:
- It *must* receive fixed-size input buffers, every time, always.
- It can only handle a fixed number of spatialized sound sources at a time.
- It has a concept of "tails"; the spatialization of a sound can continue after the sound itself ends (eg echo).
Changes to audio.c were needed to support Oculus Audio's quirks:
- audio.c now supports a "fixedBuffer" mode which invokes the generator/spatializer in fixed size chunks
- Each source now has an intptr_t "memo" field that the spatializer may use to store whatever (Oculus spatializer uses this to handle the sound source limit).
- The spatializer interface got a couple new methods: A "tail" method …
=> Oculus spatializer for miniaudio branch

CMakeLists.txt
(Build miniaudio if LOVR_ENABLE_DATA is on)
=> Fix build when LOVR_ENABLE_AUDIO is off in CMake

src/api/l_graphics_shaderBlock.c
shaderBlock:send() has two additional arguments with this patch: An offset and a size.
If present, only the range [offset…offset+size) will be sent.
Usually this is not super useful because it is usually efficient-ish to send even a large shader block all at once.
I believe the reason I added this was I had a shaderblock that was being simultaneously written into by send()s from code and written into by a compute shader, so I wanted to avoid stomping the compute-shader-owned part of the shader block.
Anyway it's nice to have.
This is an API change and will require a doc change.
=> Give shaderBlock:send() the ability to send only part of the block

src/core/util.h, src/modules/audio/audio.c, src/modules/audio/audio.h
If 64 sources are playing and a new one is started, `Source:play` will return false.  Having a cap of the number of sources is helpful for spatializers.  It also sets an upper bound on the amount of work the audio thread needs to do, which can avoid unexpected audio glitches during epic gameplay moments.
Instead of a linked list, a static list of 64 Sources is used.
Each Source has an index in the list, which as an added benefit can be used by spatializers as a unique index.  This may be able to replace the spatializerMemoField.
Bit scanning intrinsics are used to efficiently iterate the list, using a mask (need to test on windows).  I'm still on the fence about this, it's pretty ugly and difficult to understand.
=> Enforce strict limit of 64 active sources;

src/modules/data/sound.c, src/modules/data/sound.h
Allows a Sound to be created from a callback. Because Sound already has a "read" callback, this will integrate cleanly with the existing lovr.audio module. The callback will be called to generate the audio.
The callback-based Sound is allowed to be of infinite length. It is allowed to store a "memo" pointer in the Sound. It is also allowed to have a custom "destroy" callback called on destruction (which must destroy the memo pointer if appropriate).
This is of zero immediate use. It is handy to me because I have forked lovr. If this were accepted upstream, it would make a lovr fork (like mine) easier to maintain because custom audio types could be added without modifying audio.c. However, most people have not forked lovr.
In future, I would like to attempt live pcm audio generation in …
=> lovrSoundCreateFromCallback

src/lib/stdatomic/stdatomic.h, src/modules/audio/audio.c
- stdatomic.h had not defined ATOMIC_INT_LOCK_FREE, but it is now required
- It's _MSC_VER, not _MSVC_VER
=> Fix MSVC build

src/modules/headset/headset_oculus.c
I think the API for arr_t changed but the oculus driver code did not change to the new rules
=> Fix crash on startup on Oculus driver

CMakeLists.txt
Without this, building on Quest with CMake with OCULUS_AUDIO enabled will cause a crash when the apk is run.
=> CMake build fix for Oculus Audio on Quest

src/modules/physics/physics.c
ODE errors, debugs and messages are redirected into LOVR's log system
by a callback mechanism for each.
The ODE submodule is updated to revision that does not crash when error
or debug occurs.
=> Route ODE messages into LOVR log system

src/modules/audio/audio.c, src/modules/audio/audio.h
isSpatial() was removed because now the relevant concept is not "is it spatial?" but rather "does it have spatial effects?". Since all effects are currently spatial, this is the same as asking "does it have effects?".
However, the knowledge "no effects -> no spatializer use" is "magic", it's not obvious from the names and it isn't commented, and this knowledge is applied three times in audio.c. This patch encapsulates the knowledge into a UsesSpatializer() function and comments as appropriate.
Also, remove accessor prototype for old IsSpatial() function, which currently corresponds to no function.
=> Encapsulate "uses spatializer?" nature in lovrSourceUsesSpatializer

src/api/api.c
Implements #411 proposal. I needed this variant before so I think this is good extension to setColor.
When setColor() is called without arguments it will throw `bad argument #1 to 'setColor' (number expected, got no value)"`. It does not convey all possible combinations of arguments, but I think this is acceptable to keep the error message concise.
=> Allow using alpha with hexcode when setting color

CMakeLists.txt
Also add the Phonon target as a dependency when LOVR_USE_STEAM_AUDIO (all platforms), which has no effect but could be useful later if SteamAudio acquires any build steps while still being a runtime-linked library.
You'll notice the OculusAudio section is extremely complex. This is Oculus's fault.
=> Get SteamAudio and OculusAudio working on mac

CMakeLists.txt
Unsure this is ready to merge.
Problems:
- I send the same flags to all three of the C compiler, C++ compiler, and Linker. Are all three really necessary?
- It would be nice to turn on ubsan too. The problem is in order to turn on ubsan you have to block ubsan from being used in (1) ODE (2) LuaJIT. I'm not sure I understand LuaJIT well enough to selectively set CMAKE_C_FLAGS for some projects but not others.
This COULD go in master but I put it on dev because applying it to master would create a dev merge conflict.
=> Pass -DLOVR_SANITIZE to CMake config for AddressSanitizer

src/core/os_macos.c
Our permissions code currently uses AVCaptureDevice, which only became available on MacOS with 10.14. The code attempts to deal with this with a [AVCaptureDevice respondsToSelector] check, which will work at runtime, but this check will never run because the code will fail to compile (I tested on 10.13). This change #ifs out the section that can't compile on 10.13. (I set it to throw an assert if the check is compiled out but found at runtime to be needed, on the assumption failing to run is better than running with incorrect permissions.)
There are various other ways we could do this, like late-binding tricks. But in tests this works.
=> Fix compile on old macos

CMakeLists.txt
Tried to build on mac with cjson plugin. Got this error.
Bjorn suggested the fix in this patch based on the UNIX code. I tried it. It worked.
=> Fix copy so that plugins can work on mac

src/modules/audio/spatializer_oculus.c
Critical bugfix to oculus spatializer. Due to this single line being missing, lovr.audio.setPose() never did anything and possibly the oculus spatializer would start doing incorrect things when too many sounds start playing at once.
=> Fix lovr.audio.setPose() in oculus spatializer mode

src/modules/audio/spatializer_oculus.c
Oops. There's literally been no distance attenuation in the Oculus Spatializer since we merged it. This one-line fix addresses this.
=> Fix distance attenuation in Oculus spatializer

src/api/l_audio.c, src/modules/audio/audio.c, src/modules/audio/audio.h, src/modules/audio/spatializer_oculus.c, src/modules/audio/spatializer_phonon.c, src/modules/audio/spatializer_simple.c
This patch has been submitted before and rejected before, and that's okay, I'm just submitting an updated version so you can close the PR and there will be a record of it. :)
This patch allows setting the sample rate. The sample rate still cannot be changed once the program starts, but it can be set in lovr.conf with t.audio.sampleRate and queried with lovr.audio.getSampleRate().
I maintain this patch because sometimes in my fork I need to run at 44.1khz sample rate, but not all the time (so changing audio.h is slightly inconvenient).
=> Allow get sample rate in conf.lua, read back with lovr.audio.getSampleRate()

src/modules/audio/spatializer_oculus.c
In my testing, feeding the results from lovr.headset.getPose directly into lovr.audio.setPose produces, in the Oculus spatializer, a situation where spatialization works BUT everything acts as if it has been reflected "horizontally", that is, reflected across the XZ plane. Turning my head left sounds like I turned it right and vice versa. Nothing weird happens on other axes of rotation.
Patch corrects the quaternion being fed into Oculus Audio to reverse this. With this patch my tests show correct orientation on all axes.
=> Fix horizontal rotation bug in Oculus spatializer

src/resources/AndroidManifest_oculus.xml
Oculus Store is currently requiring these XML attributes for submission.
By the way, in my fork I've broken out all these various attributes onto their own indented lines— this makes merging less of a problem if individual things have changed (like, you want to change excludeFromRecents because you're making a release build, or you want to bump your version number on the top stanza). Would you be interested in this formatting chagne upstream?
=> Add new XML attributes required for Oculus

src/api/l_math_vectors.c
Vector methods are extended to receive vectors as individual numbers
for each of x,y,z,w component. The vector objects are still supported
as well.
Previously only single value scalar was supported. This change maintains
backward compatibility.
```
v = vec3():add( 1, 2, 3 )          -- both do the same
v = vec3():add( vec3(1, 2, 3) )    _/
v = vec4():mul( 2 )            -- x component is a default for y, z
v = vec4():mul( 2, 2, 2, 2 )   _/
v = vec2():lerp( 2, 2, 0.5 )         -- in case of lerp operation,
v = vec2():lerp( vec2(2, 2), 0.5 )   _/   all components are mandatory
```
=> Accept number values in Vec2/3/4 operations

src/modules/graphics/opengl.c
- When calling lovr.graphics.stencil, the color mask is initially
disabled, and gets restored to its initial state afterwards.
- However, when it's restored, it uses lovrGraphicsSetColorMask, which
just sets shadow state that doesn't make it all the way to GL until
another draw is done.
- The consequence of this is that if you call .stencil and then don't do
a draw, any clears that happen will use the old (disabled) color mask,
preventing the color buffer from being cleared.
- The solution here is to lower the color mask change down into opengl.c
where it can directly hit OpenGL.
Need to look over this to make sure there aren't any unintended consequences.
=> Fix stencil color mask;

CMakeLists.txt
dx was deprecated years ago, and d8 replaces it. dx is
removed in build-tools 31, so it's best not to depend on it.
In addition, d8 now supports Java 11 (class version 55), which
is required to use the javac bundled with Android Studio.
=> Use d8 instead of dx

src/api/l_math.c
Correcting the order of stack operations to fetch RGB components from
the table and to put in conversion the results.
Before the fix these two calls produced different results:
`lovr.math.gammaToLinear(  0.1, 0.2, 0.3  )`
`lovr.math.gammaToLinear( {0.1, 0.2, 0.3} )`
=> Fix gamma/linear conversion of a RGB table

src/core/maf.h
The arccos was incorrectly calculated when cosangle was larger than 1.0
=> Fix NaN handling when calculating angle for mat4

src/api/api.c, src/api/api.h, src/api/l_audio.c, src/api/l_data.c, src/api/l_data_image.c, src/api/l_data_modelData.c, src/api/l_data_rasterizer.c, src/api/l_data_sound.c, src/api/l_event.c, src/api/l_graphics.c, src/api/l_graphics_canvas.c, src/api/l_headset.c
These functions read an unsigned 32 bit integer from the Lua stack
and error if the value is negative or too big.  Currently converting
Lua numbers to integers will silently wrap or invoke undefined behavior
when they are outside of the acceptable range.
For projects that don't want the overhead of type/bounds checks, the
supercharge build option (LOVR_UNCHECKED) can now be used to skip all
type/bounds checks.
It may be a good idea to rename checkfloat/optfloat to checkf32 and optf32,
for consistency.
It may also be nice to support i32, u16, u8, etc., but those are seldom used.
=> Add luax_checku32 and luax_optu32;

src/api/l_math_vectors.c, src/core/maf.h
We could also consider moving vec2 and vec4 implementations to `maf.h`. With the current layout I had to repeat some of code (lenght and dot calculation) because existing Lua-facing functions could not be reused.
Some testing code:
```lua
local function lua_angle(v1, v2)
return math.acos(v1:dot(v2) / (v1:length() * v2:length()))
end
local v1 = vec2(1, 2)
local v2 = vec2(3, 4)
print(v1:angle(v2))
print(lua_angle(v1, v2))
local v1 = vec3(1, 2, 3)
local v2 = vec3(4, 5, 6)
print(v1:angle(v2))
print(lua_angle(v1, v2))
local v1 = vec4(1, 2, 3, 4)
local v2 = vec4(5, 6, 7, 8)
print(v1:angle(v2))
print(lua_angle(v1, v2))
lovr.event.push('quit')
```
=> Add Vec2/3/4:angle(other)

src/modules/graphics/opengl.c
Instead of creating images hardcoded as RGBA, always use the selected texture's format.
=> Use Texture's format when creating an Image from Canvas

src/api/l_graphics.c, src/modules/graphics/font.c, src/modules/graphics/font.h, src/modules/graphics/graphics.c
Per the discussion on https://github.com/bjornbytes/lovr/issues/536.  The default filter setting is now flowed through and used as the font filter.
However, there's a caveat: previously (before this PR) font filter was set to bilinear, as default and always. With this change, it's now configurable, _but_ the default is now trilinear (which is the default for the textures.)
Probably not an issue, but just wanted to bring this up in case it is.
I tested this on Linux and Windows and it fixes my issue.
=> Font filtering now respects the default setting.

src/modules/physics/physics.c
Fixes crash due to MAX_CONTACTS being sent to dCollide as the number of dContacts available.
=> MeshShapes gets hits on all passed surfaces. Callback for each of them.

src/modules/headset/headset_openxr.c
This change fixes a linker error I noticed when compiling on my windows
sytstem. see #551
According to this link the macro is prefered to the keyword.
https://docs.microsoft.com/en-us/cpp/c-language/static-assert-c?view=msvc-170#:~:text=The%20_Static_assert%20keyword%2C%20and%20the%20static_assert%20macro%2C%20both,runtime%20and%20incur%20a%20runtime%20cost.%20Microsoft-specific%20behavior
=> use static assert macro instead of keyword

src/api/l_physics_world.c, src/modules/physics/physics.c, src/modules/physics/physics.h
Physics world's "quick step" is executed in multiple iteration steps.
The getter and setter for this value is now made available as two new
methods in the World object.
This is allows user to balance between the less accurate but quick
simulations, and more stable behavior of physics.
Something similar was already possible, by reducing the delta time and
running the sim multiple times per frame. However, any force user applies
to collider is zeroed after each step. User would thus have to keep track
of applied forces, and re-apply them inside the physics iteration loop.
By default ODE uses 20 iterations in quick step.
=> Add `World:setStepIterations(num)` and its getter

src/modules/headset/headset_openxr.c
It's essentially replaced by KHR_loader_init_android, and will eventually not be provided by new/updated runtimes, so don't require it.
That said, it's safe to pass its struct even if the extension isn't available, since it will just be ignored if unrecognized.
=> Allow XR_KHR_android_create_instance to be optional

src/api/l_headset.c, src/modules/headset/headset.h, src/modules/headset/headset_openxr.c
OpenXR provides APIs to enumerate the list of supported refresh-rates, and
selecting a new refresh-rate. This is useful on Quest 2 because the headset
supports 60/72/80/90Hz.
This patch adds two new APIs to the lovr.headset module:
- `lovr.headset.getDisplayFrequencies()`:
This function returns a table containing the supported refresh-rates on
success; nil otherwise.
- `lovr.headset.setDisplayFrequency(refreshRate:number)`:
This function takes the new refresh-rate to select as an argument and returns
true on success, false otherwise.
Only the OpenXR backend has support for this feature and it is gated by the
"refreshRate" OpenXR feature flag, similarly to what the `getDisplayFrequency()`
API does.
```lua
function lovr.load()
supportedFrequencies = lovr.headset.getDisplayFrequencies()
if …
```
=> Add support for setting the display refresh-rate.

src/api/l_event.c, src/modules/event/event.c, src/modules/event/event.h
A null-char is valid part of Lua string. When such a string is sent through the channel, its length should be stored as well to be able to correctly reconstruct it on the other thread.
The bug was triggered with this code:
s1 = 'a \0 b'
print(#s1) -- 5
ch:push(s1)
s2 = ch:pop()
print(#s2) -- 2
=> Fix sending strings with \0 through channels

src/api/l_physics.c, src/api/l_physics_shapes.c, src/api/l_physics_world.c, src/modules/physics/physics.c, src/modules/physics/physics.h
This is sitting on my drive for too long. It works, but needs bit more effort before it's ready to merge.
It is not possible to change the pose of heightfield after creating it. I believe the `dGeomSetPosition` needs to be used (need to test), so the `setPose()` would have to be specialized for the heightfield collider case. I also skipped on using the recommended `dGeomHeightfieldDataSetBounds()` as it didn't behave correctly in my tests.
I've only tested on "r32f" heightmap image format as I can store actual terrain height into each pixel. Other formats that support `getPixel()` should be OK to use, with the `verticalScaling` parameter mapping the 0 to 1 pixel value to actual height. Changing the terrain is not implemented at the moment.
I would like to also support the callback mode …
=> Add physics heightfield shape

src/core/gpu_vk.c
There's a "portability enumeration" extension and flag you have to set to get Vulkan to work on macOS.  If you don't set it, Vulkan hides the MoltenVK runtime since it's not 100% conformant.  The flag was added unconditionally, but it needs to only be added when the extension is active.
PR since I can't test it yet.
=> gpu: only set portability enumeration flag if extension is enabled;

src/api/l_graphics_model.c, src/modules/data/modelData_gltf.c, src/modules/graphics/graphics.c
from matrix chat:
> I've noticed some off-by-ones with GLTF model node indices
> but I'm not sure which is the right place to fix it:
> * the GLTF model parser puts its nodes into the modelData->nodes array starting at zero (of course) and the root node last, but in modelData->nodeMap the indices that are stored start counting from 1
> * luax_checknode in l_data_modelData.c doesn't account for this and therefore all getNode...() APIs from there are off-by-one when using strings to access the nodes
>
>the question is, should the map in the GLTF model parser be fixed or should the map output be used - 1 for indexing model->nodes[] (and if so, why?)
> also: the animation & material maps have the same map_set call / index logic, so they might be off-by-one as well? Haven't checked their Lua …
=> GLTF fixes

src/modules/thread/thread.c
`thread->handle` is zero until `lovrThreadStart()`. tinycthread's functions should be called only if `thread->handle` exists.
=> Check for thread handle

src/modules/graphics/graphics.c
Without it drawing the second torus will crash the app
=> Check if torus shape is cached

src/api/l_physics_world.c
I was missing this when serializing/re-creating the physics scene.
Amazingly enough just about everything else about the world state and geometry was already retrievable by the API 🙌
=> A getter for World list of tags

src/modules/graphics/graphics.c
Fixes #620
Desktop rendering on macOS in windowed mode was previously constrained to 25% of the view. This was caused by using the initial window size rather than the framebuffer size when setting the viewport.
This issue has been fixed by using `os_window_get_fbsize` instead of `os_window_get_size` when setting the viewport. This ensures that the viewport is correctly set based on the framebuffer size, which takes DPI into account.
Tested on macOS 13.1 ARM64.
=> Fix constrained rendering in windowed mode on macOS #620

src/api/l_graphics_buffer.c, src/api/l_graphics_pass.c, src/modules/audio/spatializer_phonon.c, src/modules/graphics/graphics.c, src/modules/math/math.c
Address size_t narrowing warnings in MSVC by adding casts. Also adds some asserts to make sure the casts are safe.
I have not tested this patch beyond compiling it because I'm not sure how.
=> Address various MSVC warnings (casts, comparisons, function pointers)

src/api/l_math.c, src/modules/math/math.c
Light probes are neat!
While testing I noticed the light often came from wrong direction, and traced it down to few wrong signs when converting cubemap UV coordinates to 3D direction vector, and signs for SH coefficients.
I used https://www.ppsloan.org/publications/StupidSH36.pdf as a reference. Testing was done with [this script](https://gist.github.com/jmiskovic/cf2713b6b476f2c49f10e701ae3fe545).
I've also compared results with [three.js implementation](https://threejs.org/examples/?q=probe#webgl_lightprobe_cubecamera), it comes out completely identical to my eye.
=> Fix signs for light probe coefficients

src/util.h
Something I did not know until today is that in 2011 C and C++ both added a "no return" attribute, but the respective C11 and C++11 attributes are not compatible. C went with `_Noreturn` and C++ went with `[[noreturn]]`. C23 will fix this, but only by adopting `[[noreturn]]` and deprecating `_Noreturn`, so that will in some ways only make things more confusing.
I hate this, but I do need to be able to include lovr headers from C++ files, so here is a patch to use a LOVR_NORETURN on our one no-return function (`lovrThrow`) which defines to the appropriate attribute for the current language. In my tests the C and C++ files both compile fine with this change.
=> Make 0.16 util.h compile correctly when included from a C++ file 

src/api/api.h, src/api/l_graphics.c, src/api/l_graphics_buffer.c, src/api/l_graphics_pass.c, src/core/spv.c, src/core/spv.h, src/modules/graphics/graphics.c, src/modules/graphics/graphics.h
See #631 for initial idea (and also #208)
- `Pass:mesh` accepts tables for vertices/indices, instead of just Buffers
- Add `Pass:setVertexFormat` to set format used for table-based meshes
- `Pass:send` supports sending tables to uniform/storage buffers
- `Pass:send` supports arbitrarily nested structs/arrays for push constants
- Buffer formats support arbitrarily nested structs/arrays
- Zero-length buffers are valid and represent key/value structs (kinda like Lua tables)
- Fields can have real names using `name` flag
- Field types can be tables of other fields (nested structs)
- Fields can have `length` key to make them an array
- newBuffer syntax has been changed to put format first (old version still works)
- Buffers can be created from shader variables, avoiding the need to carefully …
=> Buffer Format Improvements

src/core/maf.h
A reproduction:
`print(vec3(3.0253329277039, -2.000001, -0.79650980234146):angle(vec3(3.0253329277039, -2, -0.79650980234146)))`
=> Fix acos domain error in angle between two Vec3

src/api/l_event.c, src/core/os.h, src/core/os_android.c, src/core/os_glfw.h, src/core/os_wasm.c, src/modules/event/event.h, src/modules/system/system.c
Added `lovr.wheelmoved(x, y)` callback. Scrolling right gives positive  x, scrolling up gives positive y values. This is same callback name and sign convention as LOVE2D.
GLFW implementation is tested on linux & windows. Emscripten implementation is best effort; it compiles and tries to set correct signs based on docs. xcb is not implemented.
=> Add mousewheel callback

src/core/maf.h, src/core/os_glfw.h, src/modules/headset/headset_simulator.c, src/modules/system/system.c, src/modules/system/system.h
Updates simulator controls:
- Use [mousearm](https://github.com/jmiskovic/lovr-mousearm)-style hand pose, where the controller is positioned based on the mouse
- Improved smoothing behavior, fixes slight stuttering
- Adds sprint (hold shift to move 5x faster)
~~Still need to add back velocity and make scroll change hand distance.~~
Not yet sure how to handle the discontinuity in the cursor position when releasing the mouse button.  It causes a jump in the hand position which is a bit jarring.
- Current approach is to cause the controller to lose tracking while mouse button is held.  It's slightly better, but might make testing more difficult and is still a little distracting for experiences that draw hands.
- I also tried some kind of solution where the controller stays in a fixed spot in …
=> Implement mousearm simulator controls;

etc/monkey.h, etc/monkeycrush.lua, etc/nogame.lua, src/api/l_graphics_pass.c, src/core/maf.h, src/modules/graphics/graphics.c, src/modules/graphics/graphics.h
- Adds Pass:setViewCull to enable/disable frustum culling.
- Renames Pass:setCullMode to Pass:setFaceCull (with backcompat).
- Adds `drawsCulled` pass stat.
Some stuff currently missing:
- Text is not culled, but should be.
- VR view frusta are not merged yet.
Optimizations I tried that weren't worth it:
- Detecting infiniteZ and reducing plane count to 5 made it slower (branching?)
- Putting transforms and bounds in a separate array from the draws (to avoid ever touching memory for culled draws, and reduce size of Draw struct) did have a measurable impact of 5% in the "hot" loop that actually does draws.  But draw calls are not actually a bottleneck of render pass recording right now, and so this change doesn't seem worth the extra code complexity.
- Pre-transforming bounding boxes by …
=> Frustum culling;

src/core/maf.h
The computation is different before and after that commit and it breaks my math:
`mat4(0,0,0,0,0,0,0,0,0,170,0,100,-0.75,0.84,-1,0):mul(1,1,1)`
I believe removing the w normalization in `be795c0` causes this, and the x,y,z should be divided by 100 to be correct. I don't really grok the homogeneous coordinates, but I did check with another vector math lib to confirm which is correct.
=> Restore w normalization in mat4:mul(vec3)

.github/workflows/build.yml, CMakeLists.txt, Tupfile.lua, src/core/gpu.h, src/core/gpu_vk.c, src/core/os.h, src/core/os_glfw.h, src/modules/graphics/graphics.c, src/modules/headset/headset_simulator.c
Restores ability to open window after initializing graphics module.
Surface is created lazily instead of being required upfront.
Use native platorm handles instead of GLFW callbacks.
Some minor reorganization around core/gpu present API and xr transitions.
Linux links against libxcb/libX11/libX11-xcb for XGetXCBConnection.
Still filling in and testing esp macOS.
=> Surface Improvements
